#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./colors || exit 1

readarray -t ABOUT << "EOF"
Plop, c'est moi Pumbaa :
un passionné d'informatique, de jeux vidéo,
de culture japonaise, et de plein d'autres trucs.

J'aime partager mes découvertes et créations avec les autres, 
que ce soit à travers mes blogs, ou mes projets GitHub.
EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
