#!/usr/bin/env bash
#
# Make the news section
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: December 06, 2025
# License: MIT
#
# # Contributors
# - Pumbaa <webmaster@pumbaa.ch>

. ./colors || exit

{
echo -n "${COLOR4}2026-01-01 ${COLOR5}Notre jeu de société ${COLOR3}LegendHarry${COLOR5} !${RST}"
echo " ${COLOR1}https://legendharry.pumbaa.ch${RST}"
} | ./tools/box -hp 1 -vp 1 -tc "$COLOR5" -t 'News' -bc "$COLOR4" -T plain
