#!/usr/bin/env bash
#
# Print the YSAP logo
#
# # Created
# Author: Dave Eddy <ysap@daveeddy.com>
# Date: April 05, 2025
# License: MIT
#
# # Contributors
# - Dave Eddy <ysap@daveeddy.com>
# - Joshua Rayton <joshua.rayton@gmail.com>
# - Pumbaa <webmaster@pumbaa.ch>

# ASCII art generated with https://texteditor.com/multiline-text-art/
# Colors guide : https://unix.stackexchange.com/questions/124407/what-color-codes-can-i-use-in-my-bash-ps1-prompt

. ./colors || exit

COLOR6=$'\e[38;5;029m'          # medium green
COLOR7=$'\e[38;5;022m'          # dark green
COLOR8=$'\e[38;5;049;48;5;029m' # light green (text) medium green (background)



readarray -t LOGO << EOF
AAAAAAB AAB   AABAAAB   AAABAAAAAAB  AAAAAB  AAAAAB 
AADCCAABAAF   AAFAAAAB AAAAFAADCCAABAADCCAABAADCCAAB
AAAAAADEAAF   AAFAADAAAADAAFAAAAAADEAAAAAAAFAAAAAAAF
AADCCCE AAF   AAFAAFGAADEAAFAADCCAABAADCCAAFAADCCAAF
AAF     GAAAAAADEAAF GCE AAFAAAAAADEAAF  AAFAAF  AAF
GCE      GCCCCCE GCE     GCEGCCCCCE GCE  GCEGCE  GCE
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

shopt -s extglob

for line in "${LOGO[@]}"; do
	line=${line//+(A)/$COLOR6&$RST}
	line=${line//+(B|C|D|E|F|G)/$COLOR7&$RST}
	line=${line//+(H)/$COLOR7&$RST}
	line=${line//+(I)/$COLOR8&$RST}

	line=${line//A/█}
	line=${line//B/╗}
	line=${line//C/═}
	line=${line//D/╔}
	line=${line//E/╝}
	line=${line//F/║}
	line=${line//G/╚}
	line=${line//[HI]/▄}

	echo "$line"
done

