#!/usr/bin/env bash
#
# Make the body of the index page for ysap.sh
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT
#
# # Contributors
# - Pumbaa <webmaster@pumbaa.ch>

. ./colors || exit 1

function print_two_boxes() {
	declare -a box_left
	declare -a box_right
	IFS=$'|' read -ra box_left <<< "$1"
	IFS=$'|' read -ra box_right <<< "$2"

	# get the max of both boxes
	num_about=${#box_left[@]}
	num_socials=${#box_right[@]}
	if ((num_socials > num_about)); then
		max=$num_socials
	else
		max=$num_about
	fi

	# get the length of a single "about" line
	about_stripped=$(./tools/strip-ansi <<< "${box_left[0]}")
	about_len=${#about_stripped}

	for ((i = 0; i < max; i++)); do
		line1=${box_left[i]}
		line2=${box_right[i]}

		if [[ -z $line1 ]]; then
			line1=$(./tools/repeat-char ' ' "$about_len")
		fi

		echo "$line1 $line2"
	done
}

mapfile -t ABOUT < <(./make-about | ./tools/box -t "A propos" -hp 1 -vp 1 -bc "$COLOR4" -tc "$COLOR5" -s '|')
mapfile -t SOCIALS < <(./make-socials | ./tools/box -t "Rézos" -hp 1 -vp 1 -bc "$COLOR4" -tc "$COLOR5" -s '|')
( IFS='|'; print_two_boxes "${ABOUT[*]}" "${SOCIALS[*]}" )

mapfile -t BLOGS < <(./make-blogs | ./tools/box -t "Mes blogs" -hp 1 -vp 1 -bc "$COLOR4" -tc "$COLOR5" -s '|')
mapfile -t FORUMS < <(./make-forums | ./tools/box -t "Vieux forums" -hp 1 -vp 1 -bc "$COLOR4" -tc "$COLOR5" -s '|')
( IFS='|'; print_two_boxes "${BLOGS[*]}" "${FORUMS[*]}" )

./make-github | ./tools/box -t "Mes projets GitHub les plus aboutis" -hp 1 -vp 1 -bc "$COLOR4" -tc "$COLOR5" -s '|'
