#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT
#
# # Contributors
# - Pumbaa <webmaster@pumbaa.ch>

. ./colors || exit 1

readarray -t ABOUT << "EOF"
Plop, c'est moi Pumbaa :
un passionné d'informatique, de jeux vidéo,
de culture japonaise, et de plein d'autres trucs.    
EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR5$line$RST"
done
