#!/usr/bin/env bash
#
# Generate the Legend (help message) - intended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT
#
# # Contributors
# - Pumbaa <webmaster@pumbaa.ch>

. ./colors || exit

UNDERLINE=$'\x1b[3m'

format-box() {
	local title=$1
	shift

	if [[ -z $1 ]]; then
		return
	fi
	local cmd_re='^(\$ [^ ]+)(.*)$'
	{
		echo '%'
		local line name url
		for line in "$@"; do
			IFS='%' read -r name url <<< "$line"

			if [[ $name =~ $cmd_re ]]; then
				local cmd=${BASH_REMATCH[1]}
				local rest=${BASH_REMATCH[2]}

				echo -n "$COLOR3$cmd$RST$COLOR5$rest"
			else
				echo -n "$COLOR5$name$RST"
			fi

			echo -n '%'
			echo -n "$COLOR1$UNDERLINE$url$RST"
			echo
		done
	} | ./tools/box -s '%' -hp 1 -tc "$COLOR5" -T plain -t "$title"
}

full='false'
while getopts 'f' opt; do
	case "$opt" in
		f) full='true';;
		*) exit 1;;
	esac
done

# TODO trouver une astuce de configuration apache pour ne pas devoir mettre le follow redirect (-L) dans les curls. Sinon y'a curl https://pumbaa.ch qui fonctionne
legend=(
	'$ curl -L pumbaa.ch%Get this page'
)
resources=()
extras=()

if $full; then
	legend+=(
		'$ curl -L pumbaa.ch/ping%Get a 200 with the text pong'
		'$ curl [-46] -L ip.pumbaa.ch%Get your current IP address as a string' # TODO ajouter une règles de redirection dans apache pour curl sur ip.pumbaa.ch
	)

	resources+=(
		'$ curl -L style.pumbaa.ch%Bash Style Guide for writing safe scripts'
	)

	extras+=(
		'$ curl -L xmas.pumbaa.ch | bash%Christmas tree animation'
		'$ curl -L nightfall.pumbaa.ch | bash%Music Album TUI'
	)
fi

format-box Legend "${legend[@]}"
format-box Resources "${resources[@]}"
format-box Extras "${extras[@]}"
