#!/usr/bin/env bash
#
# Print the socials - indended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT
#
# # Contributors
# - Pumbaa <webmaster@pumbaa.ch>

. ./colors || exit

readarray -t SOCIALS << "EOF"
Github        |https://github.com/pumbaa666/
YouTube       |https://www.youtube.com/@pumbaa667               
EOF

UNDERLINE=$'\x1b[3m'

for line in "${SOCIALS[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
