#!/usr/bin/env bash
#
# Generate the page as seen by `curl ysap.sh`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT
#
# # Contributors
# - Pumbaa <webmaster@pumbaa.ch>

. ./colors || exit

{
./make-header -p 7 |
    ./tools/box -hp 4 -T plain

./make-news

./make-body

./make-legend # -f # -f for full (includes Resources and Extras)

} | ./tools/rtrim-ansi-aware
